# Generated by Django 3.1.1 on 2020-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronatracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordableuser',
            name='img_url',
            field=models.URLField(default='http://example.org'),
            preserve_default=False,
        ),
    ]
