# Generated by Django 3.1.1 on 2020-09-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronatracker_api', '0002_recordableuser_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordableuser',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.UniqueConstraint(fields=('user', 'timestamp'), name='unique_recording'),
        ),
    ]
