# Generated by Django 3.1.1 on 2020-09-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coronatracker_api', '0003_auto_20200923_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordableuser',
            name='img_url',
        ),
        migrations.AddField(
            model_name='recordableuser',
            name='avatar',
            field=models.TextField(blank=True),
        ),
    ]
